name = "snd"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
site = { bucket = "./frontend" }
logpush = true

[durable_objects]
bindings = [
  {name = "PIPE", class_name = "Pipe"}
]

[[migrations]]
tag = "v1"
new_classes = ["Pipe"]

# Secrets: PUSH_PUBLIC_KEY, PUSH_PRIVATE_KEY